# Render this file with Vault Agent or the deployment secret controller.
# The password values must be bcrypt hashes generated by `nats server passwd`.
authorization {
  users: [
    {
      user: "__CONTROL_USERNAME__"
      password: "__CONTROL_PASSWORD_BCRYPT__"
      permissions: {
        publish: ["runtime.control.>", "runtime.execution.>", "$JS.API.>", "$JS.ACK.>", "_INBOX.>"]
        subscribe: ["runtime.control.>", "runtime.worker.>", "_INBOX.>"]
      }
    },
    {
      user: "__WORKER_USERNAME__"
      password: "__WORKER_PASSWORD_BCRYPT__"
      permissions: {
        publish: [
          "runtime.worker.>",
          "$JS.API.STREAM.INFO.RUNTIME_EXECUTION",
          "$JS.API.STREAM.INFO.RUNTIME_WORKER",
          "$JS.API.CONSUMER.INFO.RUNTIME_EXECUTION.>",
          "$JS.API.CONSUMER.CREATE.RUNTIME_EXECUTION.>",
          "$JS.API.CONSUMER.DURABLE.CREATE.RUNTIME_EXECUTION.>",
          "$JS.API.CONSUMER.MSG.NEXT.RUNTIME_EXECUTION.>",
          "$JS.ACK.RUNTIME_EXECUTION.>",
          "_INBOX.>"
        ]
        subscribe: ["runtime.execution.>", "$JS.FC.>", "_INBOX.>"]
      }
    }
  ]
}
