include ./nats-server.conf

cluster {
  name: agent-runtime
  port: 6222
  routes: $NATS_CLUSTER_ROUTES
  tls {
    cert_file: "/var/run/secrets/nats/tls.crt"
    key_file: "/var/run/secrets/nats/tls.key"
    ca_file: "/var/run/secrets/nats/ca.crt"
    verify: true
    timeout: 2
  }
}
