server_name: $NATS_SERVER_NAME
port: 4222

jetstream {
  store_dir: "/data/jetstream"
  max_memory_store: 1GB
  max_file_store: 100GB
}

tls {
  cert_file: "/var/run/secrets/nats/tls.crt"
  key_file: "/var/run/secrets/nats/tls.key"
  ca_file: "/var/run/secrets/nats/ca.crt"
  timeout: 2
}

include ./authorization.conf
